modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

issueTrackerURL="https://github.com/ChampionAsh5357/1.16.x-Minecraft-Tutorial/issues"

[[mods]]
modId="tutorial116x"
version="${file.jarVersion}"
displayName="Tutorials for 1.16.x"
updateJSONURL="https://championash5357.github.io/ChampionAsh5357/projects/maven/io/github/championash5357/tutorial/update.json"
displayURL="https://github.com/ChampionAsh5357/1.16.x-Minecraft-Tutorial"
logoFile="logo.png"
credits="Everyone who has supported me over the years!"
authors="\u00a7bChampionAsh5357"
description='''
This is my tutorial for programming Minecraft!
'''

[[dependencies.tutorial116x]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorial116x]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
